In [1]:
import pandas as pd
import numpy as np


In [2]:
pd.__version__

'2.1.0'

In [3]:
df = pd.read_csv('housing.csv')
df.shape

(20640, 10)

In [6]:
df['ocean_proximity'].nunique()

5

In [14]:
df[df['ocean_proximity'] == 'NEAR BAY']['median_house_value'].mean()

259212.31179039303

In [17]:
mean_total_bedrooms = df['total_bedrooms'].mean()
mean_total_bedrooms

537.8705525375618

In [18]:
df['total_bedrooms'].fillna(mean_total_bedrooms, inplace=True)
df['total_bedrooms'].mean()

537.8705525375617

In [33]:
X = df[df['ocean_proximity'] == 'ISLAND'][['housing_median_age', 'total_rooms', 'total_bedrooms']].values
X


array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [34]:
X_transpose = X.T
XTX = np.dot(X_transpose, X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [35]:
XTX_inv = np.linalg.inv(XTX)    
XTX_inv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [36]:
y = np.array([950, 1300, 800, 1000, 1300])

In [41]:
w = np.dot(np.dot(XTX_inv, X.T), y)
w

array([23.12330961, -1.48124183,  5.69922946])